; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Genco Tools"
#define MyAppVersion "1.0.6"
#define MyAppPublisher "Genco Import & Export"
#define MyAppExeName "bot_grafico.exe"
; AppId da versão antiga "Genco Search" — usado para detectar e remover a instalação anterior.
#define OldAppId "{{88747CF2-7741-4FC0-9899-927A7A66D05B}"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{F2DE4FB6-870F-418D-8AB8-BA77E0DDBEE0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequired=admin
; Uncomment the following line to run in non administrative install mode (install for current user only).
OutputBaseFilename=GencoToolsSetup
SetupIconFile=C:\Users\Daniel\Desktop\Daniel\Meus Projetos\BotDeBusca\assets\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Daniel\Desktop\Daniel\Meus Projetos\BotDeBusca\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
{ ======================================================================
  Detecta e desinstala silenciosamente a versão antiga "Genco Search".
  Usa o AppId antigo para encontrar o UninstallString no registro.
====================================================================== }

function GetOldUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
begin
  sUnInstallString := '';
  sUnInstPath := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#OldAppId}_is1';
  { Procura em HKLM primeiro (instalações admin) e depois HKCU (instalações per-user) }
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    if not RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString) then
      sUnInstallString := '';
  Result := sUnInstallString;
end;

function OldVersionInstalled(): Boolean;
begin
  Result := (GetOldUninstallString() <> '');
end;

procedure UninstallOldVersion();
var
  sUninstallString: String;
  iResultCode: Integer;
begin
  sUninstallString := GetOldUninstallString();
  if sUninstallString <> '' then begin
    sUninstallString := RemoveQuotes(sUninstallString);
    Exec(sUninstallString, '/VERYSILENT /NORESTART /SUPPRESSMSGBOXES',
         '', SW_HIDE, ewWaitUntilTerminated, iResultCode);
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  { Antes de iniciar a cópia de arquivos, remove a instalação antiga se existir }
  if CurStep = ssInstall then begin
    if OldVersionInstalled() then begin
      UninstallOldVersion();
    end;
  end;
end;
